import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { SupervisorService } from 'src/app/service/supervisor.service';
import { ActivatedRoute } from '@angular/router';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Supervisor } from 'src/app/domain/supervisor';

@Component({
  selector: 'app-edit-sup',
  template: `
  <hr/>
  <br/>
  <h3 style="text-align:center">Edit Supervisor</h3>

  <!-- for ReactiveFormsModdule -->
  <form [formGroup]="supervisorForm" (ngSubmit)="editSupervisor()">

  <!-- no need since id is autogenerated on BE
  <mat-form-field  appearance="outline">
  <mat-label>ID</mat-label>

    <input matInput formControlName="id" type="number" class="example-right-align">
  </mat-form-field>
  -->

  <mat-form-field appearance="outline">
    <mat-label>Supervisor First Name</mat-label>
    <!-- add formControlName property -->
    <input matInput formControlName="firstName" placeholder="Enter Supervisor First Name">
    <mat-hint>First Name</mat-hint>
  </mat-form-field>

  <mat-form-field appearance="outline">
    <mat-label>Supervisor Last Name</mat-label>
    <!-- add formControlName property -->
    <input matInput formControlName="lastName" placeholder="Enter Supervisor Last Name">
    <mat-hint>Last Name</mat-hint>
  </mat-form-field>

  <mat-form-field appearance="outline">
  <mat-label>Gender</mat-label>
  <!-- add formControlName property -->
  <mat-select [(value)]="gender" formControlName="gender">
    <mat-option>None</mat-option>
    <mat-option value="male">Male</mat-option>
    <mat-option value="female">Female</mat-option>
  </mat-select>
  </mat-form-field>


  <button [disabled]="!supervisorForm.valid" style="width:80%"  mat-flat-button >Submit</button>
  </form>
  `,
  styles: [`
  .mat-form-field{
    width:80%;
    margin-left: 10vh;
    margin-right: 10vh;
  }
  button {
    margin-left: 10vh;
    margin-right: 10vh;
  }
  `]
})
export class EditSupComponent implements OnInit {
  supervisorForm = new FormGroup({
    // id : new FormControl("",[Validators.required]),
    firstName : new FormControl("",[Validators.required]),
    lastName : new FormControl("",[Validators.required]),
    gender : new FormControl("",[Validators.required]),
  })

  //invoking service 
  constructor(private supervisorService : SupervisorService,
    //and ActivatedRoute for getting employee id to be updated
    private router : ActivatedRoute  ,
    //invoking snackbar
    private snackbar : MatSnackBar
  ) { }

  //storage for gender
  gender : string;


  //storage for id & employee
  id : number;
  newSupervisor : Supervisor;

  ngOnInit(): void {
    //create blank employee which will store the oldEmployee
    this.newSupervisor = new Supervisor();
    //get id of employee to be updated
    this.id = this.router.snapshot.params["id"];
    //invoking service method then subscribe to get oldEmployee
    this.supervisorService.viewSupervisorById(this.id).subscribe(sup => {
      console.log(sup);
      //set blank newEmployee to selected emp to be updated
      this.newSupervisor = sup;
    })

  }

  //editEmployee
  editSupervisor(){
    //seeting the employeeForm values to newEmployee
    this.newSupervisor = this.supervisorForm.value;
    //invoking service method then subscribe
    this.supervisorService.editSupervisor(this.id, this.newSupervisor).subscribe(sup => {
      console.log(sup)
      //clear input fields
      this.supervisorForm.reset();
    })

    //invoking snackbar
    this.snackbar.open("Successfully updated Supervisor with ID : "+this.id),
      "Close", {duration : 2000, verticalPosition : "top"}

  }

}
